/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhn_android_licenseplatedecoder_decoder_LPSegmenter */

#ifndef _Included_de_hhn_android_licenseplatedecoder_decoder_LPSegmenter
#define _Included_de_hhn_android_licenseplatedecoder_decoder_LPSegmenter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhn_android_licenseplatedecoder_decoder_LPSegmenter
 * Method:    process
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_de_hhn_android_licenseplatedecoder_decoder_LPSegmenter_process
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
